trigger:
- nomain

pool:
  vmImage: ubuntu-latest

stages:
- stage: stage1

  ## Jobs inside Stage
  jobs:

  ### CI Job
  - job: createStorage
    #### Steps inside the Job
    steps:

    - task: Bash@3
      name: createS3
      displayName: 'Create S3 bucket'
      inputs:
        targetType: 'inline'
        script: |
          cd ./az-devops/aws-ep7
          python -m venv env
          source env/bin/activate
          pip install awscli
          export AWS_ACCESS_KEY_ID="$(aws_id)"
          export AWS_SECRET_ACCESS_KEY="$(aws_key)"
          aws s3api create-bucket --bucket dl-azdevops-ep7 --region us-east-1
          deactivate

  # CD Job
  - job: uploadJob
    dependsOn: createStorage
    #### Steps inside the Job
    steps:

    - task: Bash@3
      name: uploadToS3
      displayName: 'Upload files to S3 bucket'
      inputs:
        targetType: 'inline'
        script: |
          cd ./az-devops/aws-ep7
          python -m venv env
          source env/bin/activate
          pip install awscli
          export AWS_ACCESS_KEY_ID="$(aws_id)"
          export AWS_SECRET_ACCESS_KEY="$(aws_key)"
          aws s3 sync ./data s3://dl-azdevops-ep7
          deactivate
